//! Tail-aware reconstruction-error profiles for the isolated EcBeam2 engine.
//!
//! A profile is a stable causal filter
//!
//! ```text
//! x' = A x + B e
//! z  = C x + D e
//! ```
//!
//! together with its zero-input observability Gramian `P`.  Consequently
//! `V(x) = x^T P x` is exactly the energy still stored in the filter and
//!
//! ```text
//! z^2 + V(x') - V(x) = 2 e (h^T x) + q e^2.
//! ```
//!
//! EcBeam2 accumulates that signed increment only: adding `V(x')` separately
//! would count the tail twice.  The checked-in profiles are generated by
//! `tools/gen_beam_error_profiles.py`, which balances each realization so its
//! runtime Gramian is the identity.

// Preserve the generator's full decimal output as an auditable artifact. Rust
// rounds these literals to f64 when compiling them.
#![allow(clippy::excessive_precision)]

use core::fmt;

pub(crate) const MAX_BEAM_ERROR_PROFILE_STATES: usize = 6;
pub(crate) const DSD64_44K_FAMILY_WIRE_RATE: u32 = 2_822_400;
pub(crate) const DSD64_48K_FAMILY_WIRE_RATE: u32 = 3_072_000;
pub(crate) const DSD128_44K_FAMILY_WIRE_RATE: u32 = 5_644_800;
pub(crate) const DSD128_48K_FAMILY_WIRE_RATE: u32 = 6_144_000;

pub(crate) type BeamErrorProfileState = [f64; MAX_BEAM_ERROR_PROFILE_STATES];

/// Immutable coefficient view used by offline implementation-equivalence
/// attribution.  The runtime profile remains the authority; this value merely
/// copies its exact compiled coefficients so a second implementation can
/// replay them without calling the runtime transition methods.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct BeamErrorProfileCoefficients {
    pub(crate) a: [[f64; MAX_BEAM_ERROR_PROFILE_STATES]; MAX_BEAM_ERROR_PROFILE_STATES],
    pub(crate) b: BeamErrorProfileState,
    pub(crate) c: BeamErrorProfileState,
    pub(crate) d: f64,
    pub(crate) p: [[f64; MAX_BEAM_ERROR_PROFILE_STATES]; MAX_BEAM_ERROR_PROFILE_STATES],
    pub(crate) h: BeamErrorProfileState,
    pub(crate) q: f64,
}

/// Deterministic constant-memory P² quantile estimator used by experiment
/// diagnostics at the DSD wire rate.  It performs no allocation after
/// construction and never feeds a selection decision.
#[derive(Clone, Copy, Debug)]
pub(crate) struct StreamingQuantile {
    probability: f64,
    count: u64,
    initial: [f64; 5],
    heights: [f64; 5],
    positions: [f64; 5],
    desired: [f64; 5],
}

impl StreamingQuantile {
    pub(crate) fn new(probability: f64) -> Self {
        debug_assert!(probability.is_finite() && probability > 0.0 && probability < 1.0);
        Self {
            probability,
            count: 0,
            initial: [0.0; 5],
            heights: [0.0; 5],
            positions: [1.0, 2.0, 3.0, 4.0, 5.0],
            desired: [0.0; 5],
        }
    }

    pub(crate) fn observe(&mut self, value: f64) {
        if !value.is_finite() {
            return;
        }
        if self.count < 5 {
            self.initial[self.count as usize] = value;
            self.count += 1;
            if self.count == 5 {
                self.initial.sort_by(f64::total_cmp);
                self.heights = self.initial;
                let p = self.probability;
                self.desired = [1.0, 1.0 + 2.0 * p, 1.0 + 4.0 * p, 3.0 + 2.0 * p, 5.0];
            }
            return;
        }

        self.count = self.count.wrapping_add(1);
        let cell = if value < self.heights[0] {
            self.heights[0] = value;
            0
        } else if value < self.heights[1] {
            0
        } else if value < self.heights[2] {
            1
        } else if value < self.heights[3] {
            2
        } else if value <= self.heights[4] {
            3
        } else {
            self.heights[4] = value;
            3
        };
        for position in &mut self.positions[cell + 1..] {
            *position += 1.0;
        }
        let p = self.probability;
        let increments = [0.0, p / 2.0, p, (1.0 + p) / 2.0, 1.0];
        for (desired, increment) in self.desired.iter_mut().zip(increments) {
            *desired += increment;
        }

        for index in 1..4 {
            let delta = self.desired[index] - self.positions[index];
            let direction = if delta >= 1.0
                && self.positions[index + 1] - self.positions[index] > 1.0
            {
                1.0
            } else if delta <= -1.0 && self.positions[index - 1] - self.positions[index] < -1.0 {
                -1.0
            } else {
                continue;
            };
            let left_span = self.positions[index] - self.positions[index - 1];
            let right_span = self.positions[index + 1] - self.positions[index];
            let total_span = self.positions[index + 1] - self.positions[index - 1];
            let parabolic = self.heights[index]
                + direction / total_span
                    * ((left_span + direction) * (self.heights[index + 1] - self.heights[index])
                        / right_span
                        + (right_span - direction)
                            * (self.heights[index] - self.heights[index - 1])
                            / left_span);
            if self.heights[index - 1] < parabolic && parabolic < self.heights[index + 1] {
                self.heights[index] = parabolic;
            } else {
                let neighbor = (index as isize + direction as isize) as usize;
                self.heights[index] += direction * (self.heights[neighbor] - self.heights[index])
                    / (self.positions[neighbor] - self.positions[index]);
            }
            self.positions[index] += direction;
        }
    }

    pub(crate) fn estimate(&self) -> f64 {
        if self.count == 0 {
            return 0.0;
        }
        if self.count < 5 {
            let mut values = self.initial;
            values[..self.count as usize].sort_by(f64::total_cmp);
            let rank = ((self.count - 1) as f64 * self.probability).ceil() as usize;
            return values[rank.min(self.count as usize - 1)];
        }
        self.heights[2]
    }
}

/// Fixed-capacity state-space spectral weighting plus its tail-value terms.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct BeamErrorProfile {
    a: [[f64; MAX_BEAM_ERROR_PROFILE_STATES]; MAX_BEAM_ERROR_PROFILE_STATES],
    b: BeamErrorProfileState,
    c: BeamErrorProfileState,
    d: f64,
    p: [[f64; MAX_BEAM_ERROR_PROFILE_STATES]; MAX_BEAM_ERROR_PROFILE_STATES],
    h: BeamErrorProfileState,
    q: f64,
}

impl BeamErrorProfile {
    pub(crate) fn coefficients(&self) -> BeamErrorProfileCoefficients {
        BeamErrorProfileCoefficients {
            a: self.a,
            b: self.b,
            c: self.c,
            d: self.d,
            p: self.p,
            h: self.h,
            q: self.q,
        }
    }

    /// Causal filtered output for the supplied pre-advance state.
    #[inline]
    pub(crate) fn output(&self, state: &BeamErrorProfileState, error: f64) -> f64 {
        self.d.mul_add(error, dot(&self.c, state))
    }

    /// State after applying `error`, without modifying the supplied parent.
    #[inline]
    pub(crate) fn next_state(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> BeamErrorProfileState {
        let mut next = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
        for (row, next_value) in next.iter_mut().enumerate() {
            *next_value = self.b[row].mul_add(error, dot(&self.a[row], state));
        }
        next
    }

    /// Advance a selected survivor in place, returning its causal pre-advance output.
    #[inline]
    pub(crate) fn advance(&self, state: &mut BeamErrorProfileState, error: f64) -> f64 {
        let output = self.output(state, error);
        *state = self.next_state(state, error);
        output
    }

    #[inline]
    pub(crate) fn instantaneous_output_energy(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> f64 {
        let output = self.output(state, error);
        output * output
    }

    /// Exact zero-input output energy remaining after the current state.
    #[inline]
    pub(crate) fn remaining_zero_input_energy(&self, state: &BeamErrorProfileState) -> f64 {
        let mut energy = 0.0;
        for (row, state_value) in state.iter().copied().enumerate() {
            energy = state_value.mul_add(dot(&self.p[row], state), energy);
        }
        // A PSD quadratic can become a tiny negative through roundoff only.
        if energy < 0.0 && energy > -64.0 * f64::EPSILON {
            0.0
        } else {
            energy
        }
    }

    /// Single-count signed objective increment, using the generated hot terms.
    #[inline]
    pub(crate) fn tail_adjusted_energy_increment(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> f64 {
        (2.0 * error).mul_add(dot(&self.h, state), self.q * error * error)
    }

    /// Four independent profile-state dot products evaluated across AArch64
    /// lanes. The serial FMA order within each lane is identical to `dot`.
    #[cfg(target_arch = "aarch64")]
    #[inline(always)]
    fn state_dot4(
        coefficients: &BeamErrorProfileState,
        states: &[[f64; 4]; MAX_BEAM_ERROR_PROFILE_STATES],
    ) -> [f64; 4] {
        use core::arch::aarch64::*;
        let mut result = [0.0; 4];
        // SAFETY: NEON is baseline on AArch64 and both offsets address
        // two-lane regions inside each four-element stage array.
        unsafe {
            for offset in [0usize, 2] {
                let mut dot = vdupq_n_f64(0.0);
                for stage in 0..MAX_BEAM_ERROR_PROFILE_STATES {
                    dot = vfmaq_n_f64(
                        dot,
                        vld1q_f64(states[stage].as_ptr().add(offset)),
                        coefficients[stage],
                    );
                }
                vst1q_f64(result.as_mut_ptr().add(offset), dot);
            }
        }
        result
    }

    #[cfg(target_arch = "aarch64")]
    #[inline(always)]
    pub(crate) fn tail_adjusted_energy_increment_pair4(
        &self,
        states: &[[f64; 4]; MAX_BEAM_ERROR_PROFILE_STATES],
        input: f64,
    ) -> [[f64; 4]; 2] {
        let linear = Self::state_dot4(&self.h, states);
        let errors = [1.0 - input, -1.0 - input];
        core::array::from_fn(|sign| {
            core::array::from_fn(|lane| {
                let error = errors[sign];
                (2.0 * error).mul_add(linear[lane], self.q * error * error)
            })
        })
    }

    #[cfg(target_arch = "aarch64")]
    #[inline(always)]
    pub(crate) fn output_pair4(
        &self,
        states: &[[f64; 4]; MAX_BEAM_ERROR_PROFILE_STATES],
        input: f64,
    ) -> [[f64; 4]; 2] {
        let linear = Self::state_dot4(&self.c, states);
        let errors = [1.0 - input, -1.0 - input];
        core::array::from_fn(|sign| {
            core::array::from_fn(|lane| self.d.mul_add(errors[sign], linear[lane]))
        })
    }

    #[cfg(target_arch = "aarch64")]
    #[allow(clippy::needless_range_loop)]
    #[inline(always)]
    pub(crate) fn next_state4(
        &self,
        states: &[[f64; 4]; MAX_BEAM_ERROR_PROFILE_STATES],
        errors: [f64; 4],
    ) -> [[f64; 4]; MAX_BEAM_ERROR_PROFILE_STATES] {
        use core::arch::aarch64::*;
        let mut next = [[0.0; 4]; MAX_BEAM_ERROR_PROFILE_STATES];
        // SAFETY: NEON is baseline on AArch64 and every pointer addresses a
        // complete two-lane region of a four-element stage array.
        unsafe {
            for offset in [0usize, 2] {
                let error = vld1q_f64(errors.as_ptr().add(offset));
                for row in 0..MAX_BEAM_ERROR_PROFILE_STATES {
                    let mut dot = vdupq_n_f64(0.0);
                    for stage in 0..MAX_BEAM_ERROR_PROFILE_STATES {
                        dot = vfmaq_n_f64(
                            dot,
                            vld1q_f64(states[stage].as_ptr().add(offset)),
                            self.a[row][stage],
                        );
                    }
                    let value = vfmaq_n_f64(dot, error, self.b[row]);
                    vst1q_f64(next[row].as_mut_ptr().add(offset), value);
                }
            }
        }
        next
    }

    #[cfg(target_arch = "aarch64")]
    #[allow(clippy::needless_range_loop)]
    #[inline(always)]
    pub(crate) fn next_state4_selected(
        &self,
        states: &[[f64; 4]; MAX_BEAM_ERROR_PROFILE_STATES],
        parent_indices: [usize; 4],
        errors: [f64; 4],
        next: &mut [[f64; 4]; MAX_BEAM_ERROR_PROFILE_STATES],
    ) {
        use core::arch::aarch64::*;
        // SAFETY: NEON is baseline on AArch64. Parent indices originate from
        // the fixed M4 selector and every destination store is two lanes wide.
        unsafe {
            for offset in [0usize, 2] {
                let p0 = parent_indices[offset];
                let p1 = parent_indices[offset + 1];
                let state_vectors: [float64x2_t; MAX_BEAM_ERROR_PROFILE_STATES] =
                    core::array::from_fn(|stage| {
                        let value = vdupq_n_f64(states[stage][p0]);
                        vsetq_lane_f64::<1>(states[stage][p1], value)
                    });
                let error = vld1q_f64(errors.as_ptr().add(offset));
                for row in 0..MAX_BEAM_ERROR_PROFILE_STATES {
                    let mut dot = vdupq_n_f64(0.0);
                    for (stage, state) in state_vectors.iter().copied().enumerate() {
                        dot = vfmaq_n_f64(dot, state, self.a[row][stage]);
                    }
                    let value = vfmaq_n_f64(dot, error, self.b[row]);
                    vst1q_f64(next[row].as_mut_ptr().add(offset), value);
                }
            }
        }
    }

    /// Advance one profile by pairing independent output rows in NEON lanes.
    /// Each lane accumulates stages in the same order as `next_state`, so this
    /// is an exact scheduling change rather than an algebraic rewrite.
    #[cfg(target_arch = "aarch64")]
    #[allow(clippy::needless_range_loop)]
    #[inline(always)]
    pub(crate) fn next_state_row_pairs(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> BeamErrorProfileState {
        use core::arch::aarch64::*;
        let mut next = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
        // SAFETY: the fixed profile order is six, so each iteration writes one
        // complete two-row pair inside `next`.
        unsafe {
            for row in (0..MAX_BEAM_ERROR_PROFILE_STATES).step_by(2) {
                let mut dot = vdupq_n_f64(0.0);
                for stage in 0..MAX_BEAM_ERROR_PROFILE_STATES {
                    let coefficient = vsetq_lane_f64::<1>(
                        self.a[row + 1][stage],
                        vdupq_n_f64(self.a[row][stage]),
                    );
                    dot = vfmaq_f64(dot, vdupq_n_f64(state[stage]), coefficient);
                }
                let b = vsetq_lane_f64::<1>(self.b[row + 1], vdupq_n_f64(self.b[row]));
                let value = vfmaq_n_f64(dot, b, error);
                next[row] = vgetq_lane_f64::<0>(value);
                next[row + 1] = vgetq_lane_f64::<1>(value);
            }
        }
        next
    }

    /// Advance the committed reconstruction and ultrasonic filters together,
    /// using one NEON lane per profile while preserving each scalar dot/FMA
    /// chain. Lean playback needs only the ultrasonic pre-advance output.
    #[cfg(target_arch = "aarch64")]
    #[inline(always)]
    pub(crate) fn advance_profile_pair(
        reconstruction: &Self,
        reconstruction_state: &mut BeamErrorProfileState,
        ultrasonic: &Self,
        ultrasonic_state: &mut BeamErrorProfileState,
        error: f64,
    ) -> f64 {
        use core::arch::aarch64::*;
        let ultrasonic_output = ultrasonic.output(ultrasonic_state, error);
        let mut next_reconstruction = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
        let mut next_ultrasonic = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
        // SAFETY: NEON is baseline on AArch64. Each vector lane represents one
        // independent scalar profile and is extracted without horizontal math.
        unsafe {
            let states: [float64x2_t; MAX_BEAM_ERROR_PROFILE_STATES] =
                core::array::from_fn(|stage| {
                    let value = vdupq_n_f64(reconstruction_state[stage]);
                    vsetq_lane_f64::<1>(ultrasonic_state[stage], value)
                });
            for row in 0..MAX_BEAM_ERROR_PROFILE_STATES {
                let mut dot = vdupq_n_f64(0.0);
                for (stage, state) in states.iter().copied().enumerate() {
                    let coefficient = vsetq_lane_f64::<1>(
                        ultrasonic.a[row][stage],
                        vdupq_n_f64(reconstruction.a[row][stage]),
                    );
                    dot = vfmaq_f64(dot, state, coefficient);
                }
                let b = vsetq_lane_f64::<1>(ultrasonic.b[row], vdupq_n_f64(reconstruction.b[row]));
                let next = vfmaq_n_f64(dot, b, error);
                next_reconstruction[row] = vgetq_lane_f64::<0>(next);
                next_ultrasonic[row] = vgetq_lane_f64::<1>(next);
            }
        }
        *reconstruction_state = next_reconstruction;
        *ultrasonic_state = next_ultrasonic;
        ultrasonic_output
    }

    /// Definition-form increment used by diagnostics and exact-oracle checks.
    #[inline]
    pub(crate) fn tail_adjusted_energy_increment_from_definition(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> f64 {
        let next = self.next_state(state, error);
        self.instantaneous_output_energy(state, error) + self.remaining_zero_input_energy(&next)
            - self.remaining_zero_input_energy(state)
    }

    #[cfg(test)]
    fn impulse_energy(&self) -> f64 {
        self.q
    }
}

#[inline]
fn dot(left: &BeamErrorProfileState, right: &BeamErrorProfileState) -> f64 {
    let mut result = 0.0;
    for index in 0..MAX_BEAM_ERROR_PROFILE_STATES {
        result = left[index].mul_add(right[index], result);
    }
    result
}

/// Reconstruction and complementary ultrasonic profiles for one wire family.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct BeamErrorProfiles {
    pub(crate) reconstruction: BeamErrorProfile,
    pub(crate) ultrasonic: BeamErrorProfile,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct UnsupportedBeamErrorWireRate {
    pub(crate) wire_rate: u32,
}

impl fmt::Display for UnsupportedBeamErrorWireRate {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "EcBeam2 supports DSD64/DSD128 wire rates 2822400, 3072000, 5644800, and 6144000 Hz (got {})",
            self.wire_rate
        )
    }
}

impl std::error::Error for UnsupportedBeamErrorWireRate {}

/// Select the physical-frequency profile from the actual DSD wire rate.
pub(crate) fn profiles_for_wire_rate(
    wire_rate: u32,
) -> Result<BeamErrorProfiles, UnsupportedBeamErrorWireRate> {
    match wire_rate {
        DSD64_44K_FAMILY_WIRE_RATE => Ok(BeamErrorProfiles {
            reconstruction: RECONSTRUCTION_2822400,
            ultrasonic: ULTRASONIC_2822400,
        }),
        DSD64_48K_FAMILY_WIRE_RATE => Ok(BeamErrorProfiles {
            reconstruction: RECONSTRUCTION_3072000,
            ultrasonic: ULTRASONIC_3072000,
        }),
        DSD128_44K_FAMILY_WIRE_RATE => Ok(BeamErrorProfiles {
            reconstruction: RECONSTRUCTION_5644800,
            ultrasonic: ULTRASONIC_5644800,
        }),
        DSD128_48K_FAMILY_WIRE_RATE => Ok(BeamErrorProfiles {
            reconstruction: RECONSTRUCTION_6144000,
            ultrasonic: ULTRASONIC_6144000,
        }),
        _ => Err(UnsupportedBeamErrorWireRate { wire_rate }),
    }
}

const IDENTITY_PROFILE_GRAMIAN: [[f64; MAX_BEAM_ERROR_PROFILE_STATES];
    MAX_BEAM_ERROR_PROFILE_STATES] = [
    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
];

// Generated by tools/gen_beam_error_profiles.py --rust; do not hand edit.
// wire_rate=2822400; sixth-order strict-minimum-phase linear-power fit
const RECONSTRUCTION_2822400: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.99366868234138228e-01,
            3.55789639519024092e-02,
            -3.51940698806174623e-14,
            -2.66453525910037570e-14,
            2.33146835171282873e-15,
            2.66453525910037570e-14,
        ],
        [
            -3.54443800288459371e-02,
            9.95586580705389634e-01,
            1.59321782158547975e-02,
            -2.92548034118880196e-02,
            -7.72745449824852049e-03,
            9.57789188976132522e-03,
        ],
        [
            1.17827525991990711e-03,
            -3.30962210708361376e-02,
            9.75043142319767742e-01,
            5.35348731456153359e-03,
            -2.11307502724631391e-02,
            2.61907775328928949e-02,
        ],
        [
            1.27934048050194071e-04,
            -3.59350117988899327e-03,
            -9.43269764203619326e-02,
            9.13275214618011977e-01,
            -3.81523765967610728e-02,
            4.72884490560065984e-02,
        ],
        [
            4.16793927081173811e-04,
            -1.17071998546402056e-02,
            -2.92431686073887469e-02,
            -5.92977737028238111e-02,
            9.69669425475885416e-01,
            9.74446239077959575e-02,
        ],
        [
            1.34153435398841548e-04,
            -3.76819568941301562e-03,
            -9.41249686170381530e-03,
            -1.90861707353706285e-02,
            -8.23535844059787997e-02,
            9.92676954652308652e-01,
        ],
    ],
    b: [
        1.38288593313494024e-01,
        2.67704140870491823e-04,
        2.34373709538167330e-03,
        2.54476847963327167e-04,
        8.29055333043605697e-04,
        2.66847988506968515e-04,
    ],
    c: [
        2.82173461395157296e-03,
        -7.92588589129163273e-02,
        -1.97979038847704070e-01,
        -4.01451580063300506e-01,
        -2.25825743513155680e-01,
        4.56411954068300374e-02,
    ],
    d: 5.61278362790229145e-03,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        1.38210563058241004e-01,
        4.65262994522879034e-03,
        1.12753644203594317e-03,
        -2.07039216503935534e-03,
        -5.46879807187183420e-04,
        6.77837141695683976e-04,
    ],
    q: 1.91616264488182649e-02,
};
const ULTRASONIC_2822400: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.95522989413672010e-01,
            9.45197204231273957e-02,
            -2.66453525910037570e-15,
            -3.55271367880050093e-15,
            3.38618022510672745e-15,
            -1.77635683940025046e-15,
        ],
        [
            -8.65605612723197165e-02,
            9.11693648027989023e-01,
            6.69061281644683925e-02,
            -1.68025377179397140e-02,
            -3.59163710202907716e-02,
            7.31573341289504242e-03,
        ],
        [
            -5.99663031165225107e-03,
            6.31591302591717474e-02,
            9.48775679659470295e-01,
            5.24402360262108402e-02,
            2.76888600004974172e-02,
            -5.63988823249594873e-03,
        ],
        [
            2.56027966477071021e-03,
            -2.69659839681875048e-02,
            -1.83856122615641028e-02,
            9.93612231265348367e-01,
            -9.80285170091693692e-03,
            1.99672315730659022e-03,
        ],
        [
            -3.00958835341875314e-03,
            3.16982993716829059e-02,
            -2.48041896492215974e-02,
            7.92647473845253109e-03,
            9.97668570320952575e-01,
            5.04296612008552358e-02,
        ],
        [
            1.71616487271185770e-03,
            -1.80753982000864781e-02,
            1.41441532772154013e-02,
            -4.51993293206282010e-03,
            -4.98372936158993293e-02,
            9.98345080458602818e-01,
        ],
    ],
    b: [
        -2.17608653999283364e-01,
        1.98249000982063162e-01,
        -1.49365777747945905e-01,
        6.37721759564979784e-02,
        -7.49636848941668266e-02,
        4.27467240156895675e-02,
    ],
    c: [
        3.72388148321523352e-02,
        -3.92215466761539899e-01,
        3.06911948393107148e-01,
        -9.80773748415342261e-02,
        4.57311511894633801e-03,
        -2.59737251402378244e-02,
    ],
    d: 9.27555018525684227e-01,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        -1.97895976752011954e-01,
        -2.17929756224100796e-01,
        1.57518712918317594e-01,
        -3.95586202294236841e-02,
        -8.45587794575163171e-02,
        1.72236078049108100e-02,
    ],
    q: 9.80838367533409139e-01,
};
// wire_rate=3072000; sixth-order strict-minimum-phase linear-power fit
const RECONSTRUCTION_3072000: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.99465591297859945e-01,
            3.26884048497149138e-02,
            -3.04201108747292892e-14,
            0.00000000000000000e+00,
            9.54791801177634625e-15,
            3.01980662698042579e-14,
        ],
        [
            -3.25751609651086516e-02,
            9.96003098508230988e-01,
            1.44426733638307603e-02,
            -2.70476867001505639e-02,
            -7.08142135574152398e-03,
            8.89290421472743731e-03,
        ],
        [
            9.96332827246603197e-04,
            -3.04634130325861611e-02,
            9.76771967647122041e-01,
            4.67060112719330789e-03,
            -1.94239237866802306e-02,
            2.43927151106539952e-02,
        ],
        [
            1.09180902325783097e-04,
            -3.33826491696790273e-03,
            -8.72926626072431933e-02,
            9.20295590315765133e-01,
            -3.49313710956764556e-02,
            4.38670884883585188e-02,
        ],
        [
            3.53697758742220134e-04,
            -1.08144995513606360e-02,
            -2.73154332569944536e-02,
            -5.46220698750238196e-02,
            9.72347422994416233e-01,
            8.98532791751414095e-02,
        ],
        [
            1.13949680039516170e-04,
            -3.48407286505640406e-03,
            -8.80012610440026113e-03,
            -1.75974182236515661e-02,
            -7.57437191293849066e-02,
            9.93573994208784894e-01,
        ],
    ],
    b: [
        1.32551722800681893e-01,
        2.55132645095435331e-04,
        2.24468788957294784e-03,
        2.45979097066092479e-04,
        7.96863311040134706e-04,
        2.56722914081113128e-04,
    ],
    c: [
        2.49960267048628029e-03,
        -7.64266984746572592e-02,
        -1.93039758457827421e-01,
        -3.86017350555521221e-01,
        -2.17153728908703381e-01,
        4.62460431390540050e-02,
    ],
    d: 5.63147945118966636e-03,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        1.32489225895339208e-01,
        4.07790778454135503e-03,
        1.06363554015340188e-03,
        -1.99193598912375969e-03,
        -5.21513658801742793e-04,
        6.54920923535080033e-04,
    ],
    q: 1.76075378981334595e-02,
};
const ULTRASONIC_3072000: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.96219987111086058e-01,
            8.68662033266556222e-02,
            2.66453525910037570e-15,
            0.00000000000000000e+00,
            -1.38777878078144568e-15,
            3.55271367880050093e-15,
        ],
        [
            -8.01096290668890237e-02,
            9.18732609233277597e-01,
            6.17423259219490594e-02,
            -1.57165295022032581e-02,
            -3.31656116173836280e-02,
            6.89868043221508742e-03,
        ],
        [
            -5.08982110064463977e-03,
            5.83723164717361853e-02,
            9.52798445232524327e-01,
            4.83890957101920094e-02,
            2.55613294632389687e-02,
            -5.31693627196361263e-03,
        ],
        [
            2.17320061063019801e-03,
            -2.49232244693648984e-02,
            -1.68078558064856005e-02,
            9.94101431474020858e-01,
            -9.05981873778921587e-03,
            1.88450600434464377e-03,
        ],
        [
            -2.55626183837524921e-03,
            2.93163398209347129e-02,
            -2.28998153547855243e-02,
            7.39039124782010781e-03,
            9.98024355668499563e-01,
            4.63243671168243054e-02,
        ],
        [
            1.45761064134854461e-03,
            -1.67165226374246176e-02,
            1.30577447290250032e-02,
            -4.21408823025679752e-03,
            -4.58330231776906821e-02,
            9.98580840803557246e-01,
        ],
    ],
    b: [
        -2.08612420057521508e-01,
        1.91084889775056610e-01,
        -1.43946901433577024e-01,
        6.14609998874289243e-02,
        -7.22944802206088033e-02,
        4.12231650523324014e-02,
    ],
    c: [
        3.29984306907863539e-02,
        -3.78440578021352336e-01,
        2.95610550716114695e-01,
        -9.54015389612785647e-02,
        3.36151833247158756e-03,
        -2.47172900173415755e-02,
    ],
    d: 9.33239451089434846e-01,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        -1.91225042712663690e-01,
        -2.08483964734728022e-01,
        1.51681853938419126e-01,
        -3.86106661321721292e-02,
        -8.14776797278498888e-02,
        1.69479303228524704e-02,
    ],
    q: 9.82392456119101309e-01,
};

// wire_rate=5644800; sixth-order strict-minimum-phase linear-power fit
const RECONSTRUCTION_5644800: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.99841707054525575e-01,
            1.77921565385119607e-02,
            -8.28226376370366779e-14,
            -6.75015598972095177e-14,
            1.42108547152020037e-14,
            4.61852778244065121e-14,
        ],
        [
            -1.77591304378102825e-02,
            9.97985784032301870e-01,
            7.29230266950242623e-03,
            -1.51928727952821419e-02,
            -3.80279963479657201e-03,
            5.10545909420301314e-03,
        ],
        [
            2.97890521105779549e-04,
            -1.67401498796693679e-02,
            9.86463301937086978e-01,
            1.83651519977345856e-03,
            -1.05990641287689868e-02,
            1.42298026567289071e-02,
        ],
        [
            3.41298437790361550e-05,
            -1.91794857422766612e-03,
            -4.93023646552112685e-02,
            9.56600058561882793e-01,
            -1.86617930255366105e-02,
            2.50544414638405044e-02,
        ],
        [
            1.07766527168238422e-04,
            -6.05600946989236395e-03,
            -1.61687475995272861e-02,
            -3.01176940775323213e-02,
            9.85548405414172435e-01,
            4.98360992385435964e-02,
        ],
        [
            3.48659083723974690e-05,
            -1.95931219858283935e-03,
            -5.23110549365172432e-03,
            -9.74403453175974252e-03,
            -4.14422993880834908e-02,
            9.97363390217310464e-01,
        ],
    ],
    b: [
        9.77848351342528732e-02,
        1.84967374969236941e-04,
        1.66838003461478469e-03,
        1.91149250852828793e-04,
        6.03562415010162716e-04,
        1.95271689751312443e-04,
    ],
    c: [
        1.03507850890481004e-03,
        -5.81669041095078526e-02,
        -1.55297972347664515e-01,
        -2.89275145971403413e-01,
        -1.62793772737930692e-01,
        4.38902383908452154e-02,
    ],
    d: 5.79711067040856922e-03,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        9.77726474602488432e-02,
        1.55486459987884428e-03,
        7.26660538089721393e-04,
        -1.51393347360814453e-03,
        -3.78939897761658103e-04,
        5.08746799953805804e-04,
    ],
    q: 9.59873713588541878e-03,
};
const ULTRASONIC_5644800: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.98879282307999938e-01,
            4.73305332301912074e-02,
            2.22044604925031308e-16,
            0.00000000000000000e+00,
            -1.77635683940025046e-15,
            -7.10542735760100186e-15,
        ],
        [
            -4.52706837263784634e-02,
            9.55407534714937445e-01,
            3.43772027979256656e-02,
            -9.37036619821896011e-03,
            -1.85239992456140978e-02,
            4.27703517321020854e-03,
        ],
        [
            -1.55102277567442009e-03,
            3.27332994427553328e-02,
            9.73904962659679629e-01,
            2.69455134499949622e-02,
            1.42603629819143540e-02,
            -3.29259752426125374e-03,
        ],
        [
            6.62155573040476499e-04,
            -1.39743509830786237e-02,
            -8.90372059352120132e-03,
            9.96696315023695378e-01,
            -5.08535045154528964e-03,
            1.17416452371088553e-03,
        ],
        [
            -7.81726444731011406e-04,
            1.64978143448436879e-02,
            -1.27835220319241494e-02,
            4.33662769132358433e-03,
            9.99398259773107367e-01,
            2.51782730480201167e-02,
        ],
        [
            4.45617085230747196e-04,
            -9.40445086715333521e-03,
            7.28714739695065367e-03,
            -2.47206091665930217e-03,
            -2.50694024129900321e-02,
            9.99516299403107267e-01,
        ],
    ],
    b: [
        -1.53990593685301325e-01,
        1.45035804835366711e-01,
        -1.09208874973523495e-01,
        4.66229550740928089e-02,
        -5.50420450976540909e-02,
        3.13762900908143016e-02,
    ],
    c: [
        1.36781131127502592e-02,
        -2.88667438901307805e-01,
        2.23677299790158962e-01,
        -7.58793366779598744e-02,
        -1.51199712919999375e-03,
        -1.73985317168770803e-02,
    ],
    d: 9.63087949597785209e-01,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        -1.46953391105049902e-01,
        -1.52161730579631671e-01,
        1.14564929080689271e-01,
        -3.12275360301723232e-02,
        -6.17327905453851425e-02,
        1.42535806126203000e-02,
    ],
    q: 9.90401262909478941e-01,
};
// wire_rate=6144000; sixth-order strict-minimum-phase linear-power fit
const RECONSTRUCTION_6144000: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.99866390697300877e-01,
            1.63462764553088391e-02,
            -2.15716333684667916e-13,
            -1.42108547152020037e-13,
            4.11892742135933076e-14,
            1.70530256582424045e-13,
        ],
        [
            -1.63184429559781810e-02,
            9.98163875714041859e-01,
            6.64891698192482394e-03,
            -1.39995159683792281e-02,
            -3.48839989793087168e-03,
            4.71445270395065563e-03,
        ],
        [
            2.51676747926723966e-04,
            -1.53945225543478392e-02,
            9.87481428935147010e-01,
            1.62540370479291596e-03,
            -9.73745063318687265e-03,
            1.31598302401840783e-02,
        ],
        [
            2.89650571195038235e-05,
            -1.77172992255923657e-03,
            -4.54581205006889394e-02,
            9.60123542657502438e-01,
            -1.71116310058827548e-02,
            2.31257818431487294e-02,
        ],
        [
            9.12072606525532074e-05,
            -5.57895094720794842e-03,
            -1.49720816647313116e-02,
            -2.77044969756036763e-02,
            9.86778684285691265e-01,
            4.58701850337064343e-02,
        ],
        [
            2.95229018470187011e-05,
            -1.80585207850052394e-03,
            -4.84631699571866532e-03,
            -8.96767580870084374e-03,
            -3.80932823025290773e-02,
            9.97655529699855159e-01,
        ],
    ],
    b: [
        9.37282481501884451e-02,
        1.76684932833604067e-04,
        1.59762669057544968e-03,
        1.83868190960748308e-04,
        5.78977419221853896e-04,
        1.87409350933620252e-04,
    ],
    c: [
        9.14222577748252684e-04,
        -5.59210185636106888e-02,
        -1.50073744084154137e-01,
        -2.77698030387518724e-01,
        -1.56259192649566586e-01,
        4.30018743180340390e-02,
    ],
    d: 5.80342206170908828e-03,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        9.37186133318440862e-02,
        1.35544611534241591e-03,
        6.89925128737111336e-04,
        -1.45266031682945193e-03,
        -3.61973950672709092e-04,
        4.89195367221092288e-04,
    ],
    q: 8.82165198216599937e-03,
};
const ULTRASONIC_6144000: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.99053952608827234e-01,
            4.34879267921459700e-02,
            9.65894031423886190e-15,
            0.00000000000000000e+00,
            -1.55431223447521916e-15,
            7.10542735760100186e-15,
        ],
        [
            -4.17443902620973084e-02,
            9.58999454950206331e-01,
            3.16545142037129024e-02,
            -8.68070412870025621e-03,
            -1.70622534722622010e-02,
            3.97488251952893279e-03,
        ],
        [
            -1.31276847132934683e-03,
            3.01584054905634606e-02,
            9.75988279611448628e-01,
            2.48103779159691840e-02,
            1.31336840121185627e-02,
            -3.05966917451172549e-03,
        ],
        [
            5.60488017687028862e-04,
            -1.28761661170081494e-02,
            -8.15819544719897233e-03,
            9.96956357936406357e-01,
            -4.68587516942742255e-03,
            1.09163794226674327e-03,
        ],
        [
            -6.61883247190030968e-04,
            1.52055322717755195e-02,
            -1.17738652678543443e-02,
            4.01272634262135955e-03,
            9.99489884580088472e-01,
            2.31291563682987089e-02,
        ],
        [
            3.77302756374554393e-04,
            -8.66782663353313221e-03,
            6.71162450115414186e-03,
            -2.28743168236306832e-03,
            -2.30443005407238097e-02,
            9.99581524582326741e-01,
        ],
    ],
    b: [
        -1.47606780269074478e-01,
        1.39400892244835872e-01,
        -1.04959719620475234e-01,
        4.48126737287313226e-02,
        -5.29195220359182095e-02,
        3.01664706199091213e-02,
    ],
    c: [
        1.20825371361294315e-02,
        -2.77573739973501155e-01,
        2.14929392666424995e-01,
        -7.32514612776222207e-02,
        -1.83282830663999106e-03,
        -1.65971352821243645e-02,
    ],
    d: 9.66034558118043729e-01,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        -1.41404880870246191e-01,
        -1.45688138865641442e-01,
        1.10062375008800242e-01,
        -3.01827065481862292e-02,
        -5.93252554145803079e-02,
        1.38206199485344933e-02,
    ],
    q: 9.91178348050081537e-01,
};

#[cfg(test)]
mod tests {
    use super::*;

    fn all_profiles() -> [BeamErrorProfile; 8] {
        [
            RECONSTRUCTION_2822400,
            ULTRASONIC_2822400,
            RECONSTRUCTION_3072000,
            ULTRASONIC_3072000,
            RECONSTRUCTION_5644800,
            ULTRASONIC_5644800,
            RECONSTRUCTION_6144000,
            ULTRASONIC_6144000,
        ]
    }

    fn deterministic_error(sample: usize) -> f64 {
        let phase = sample as f64 * 0.173_205_080_756_887_73;
        (phase.sin() * 0.71 + (phase * 0.37).cos() * 0.19).clamp(-1.0, 1.0)
    }

    #[test]
    fn beam_error_profile_selects_only_supported_wire_families() {
        assert!(profiles_for_wire_rate(DSD64_44K_FAMILY_WIRE_RATE).is_ok());
        assert!(profiles_for_wire_rate(DSD64_48K_FAMILY_WIRE_RATE).is_ok());
        assert!(profiles_for_wire_rate(DSD128_44K_FAMILY_WIRE_RATE).is_ok());
        assert!(profiles_for_wire_rate(DSD128_48K_FAMILY_WIRE_RATE).is_ok());
        for unsupported in [0, 44_100, 11_289_600, 12_288_000] {
            let error = profiles_for_wire_rate(unsupported).unwrap_err();
            assert_eq!(error.wire_rate, unsupported);
        }
    }

    #[test]
    fn beam_error_profile_hot_increment_matches_lyapunov_definition() {
        for profile in all_profiles() {
            let mut state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            for sample in 0..4096 {
                let error = deterministic_error(sample);
                let hot = profile.tail_adjusted_energy_increment(&state, error);
                let definition =
                    profile.tail_adjusted_energy_increment_from_definition(&state, error);
                let tolerance = 2.0e-9 * (1.0 + hot.abs() + definition.abs());
                assert!(
                    (hot - definition).abs() <= tolerance,
                    "{hot} != {definition}"
                );
                profile.advance(&mut state, error);
            }
        }
    }

    #[test]
    fn beam_error_profile_telescopes_without_counting_terminal_tail_twice() {
        for profile in all_profiles() {
            let mut state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut objective = 0.0;
            let mut observed = 0.0;
            let initial_tail = profile.remaining_zero_input_energy(&state);
            for sample in 0..2048 {
                let error = deterministic_error(sample);
                objective += profile.tail_adjusted_energy_increment(&state, error);
                observed += profile.instantaneous_output_energy(&state, error);
                profile.advance(&mut state, error);
            }
            let expected = observed + profile.remaining_zero_input_energy(&state) - initial_tail;
            assert!((objective - expected).abs() <= 2.0e-7 * (1.0 + expected.abs()));
        }
    }

    #[test]
    fn beam_error_profile_impulse_energy_is_q_and_tail_converges() {
        for profile in all_profiles() {
            let mut state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut energy = 0.0;
            for sample in 0..16_384 {
                let error = if sample == 0 { 1.0 } else { 0.0 };
                energy += profile.instantaneous_output_energy(&state, error);
                profile.advance(&mut state, error);
            }
            let tail = profile.remaining_zero_input_energy(&state);
            assert!(tail < 1.0e-20, "tail did not converge: {tail}");
            assert!((energy + tail - profile.impulse_energy()).abs() < 2.0e-10);
        }
    }

    #[test]
    fn beam_error_profile_streaming_matches_impulse_convolution() {
        for profile in all_profiles() {
            let mut impulse_state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let impulse: Vec<_> = (0..256)
                .map(|sample| {
                    let error = if sample == 0 { 1.0 } else { 0.0 };
                    let output = profile.output(&impulse_state, error);
                    profile.advance(&mut impulse_state, error);
                    output
                })
                .collect();
            let input: Vec<_> = (0..128).map(deterministic_error).collect();
            let mut streaming_state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            for sample in 0..input.len() {
                let streaming = profile.output(&streaming_state, input[sample]);
                profile.advance(&mut streaming_state, input[sample]);
                let convolution: f64 = (0..=sample)
                    .map(|lag| impulse[lag] * input[sample - lag])
                    .sum();
                assert!((streaming - convolution).abs() < 2.0e-12);
            }
        }
    }

    #[test]
    fn beam_error_profile_power_pair_is_complementary() {
        for wire_rate in [
            DSD64_44K_FAMILY_WIRE_RATE,
            DSD64_48K_FAMILY_WIRE_RATE,
            DSD128_44K_FAMILY_WIRE_RATE,
            DSD128_48K_FAMILY_WIRE_RATE,
        ] {
            let profiles = profiles_for_wire_rate(wire_rate).unwrap();
            assert!(
                (profiles.reconstruction.impulse_energy() + profiles.ultrasonic.impulse_energy()
                    - 1.0)
                    .abs()
                    < 1.0e-7
            );

            let mut low_state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut high_state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut low = Vec::with_capacity(8192);
            let mut high = Vec::with_capacity(8192);
            for sample in 0..8192 {
                let error = if sample == 0 { 1.0 } else { 0.0 };
                low.push(profiles.reconstruction.output(&low_state, error));
                high.push(profiles.ultrasonic.output(&high_state, error));
                profiles.reconstruction.advance(&mut low_state, error);
                profiles.ultrasonic.advance(&mut high_state, error);
            }
            for lag in 1..=32 {
                let autocorrelation: f64 = (0..low.len() - lag)
                    .map(|sample| {
                        low[sample] * low[sample + lag] + high[sample] * high[sample + lag]
                    })
                    .sum();
                assert!(
                    autocorrelation.abs() < 2.0e-9,
                    "lag {lag}: {autocorrelation}"
                );
            }
        }
    }

    #[test]
    fn beam_error_profile_signed_increment_can_be_negative() {
        for profile in all_profiles() {
            let mut state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut saw_negative = false;
            for sample in 0..4096 {
                let error = deterministic_error(sample);
                saw_negative |= profile.tail_adjusted_energy_increment(&state, error) < 0.0;
                profile.advance(&mut state, error);
            }
            assert!(saw_negative);
        }
    }

    #[test]
    fn streaming_quantile_tracks_extreme_calibration_percentiles() {
        let mut p999 = StreamingQuantile::new(0.999);
        let mut p9999 = StreamingQuantile::new(0.9999);
        for value in 0..100_000 {
            let value = value as f64;
            p999.observe(value);
            p9999.observe(value);
        }
        assert!((p999.estimate() - 99_899.0).abs() < 250.0);
        assert!((p9999.estimate() - 99_989.0).abs() < 100.0);
        assert!(p9999.estimate() >= p999.estimate());
    }
}
