//! Tail-aware reconstruction-error profiles for the isolated EcBeam2 engine.
//!
//! A profile is a stable causal filter
//!
//! ```text
//! x' = A x + B e
//! z  = C x + D e
//! ```
//!
//! together with its zero-input observability Gramian `P`.  Consequently
//! `V(x) = x^T P x` is exactly the energy still stored in the filter and
//!
//! ```text
//! z^2 + V(x') - V(x) = 2 e (h^T x) + q e^2.
//! ```
//!
//! EcBeam2 accumulates that signed increment only: adding `V(x')` separately
//! would count the tail twice.  The checked-in profiles are generated by
//! `tools/gen_beam_error_profiles.py`, which balances each realization so its
//! runtime Gramian is the identity.

// Preserve the generator's full decimal output as an auditable artifact. Rust
// rounds these literals to f64 when compiling them.
#![allow(clippy::excessive_precision)]

use core::fmt;

pub(crate) const MAX_BEAM_ERROR_PROFILE_STATES: usize = 6;
pub(crate) const DSD64_44K_FAMILY_WIRE_RATE: u32 = 2_822_400;
pub(crate) const DSD64_48K_FAMILY_WIRE_RATE: u32 = 3_072_000;

pub(crate) type BeamErrorProfileState = [f64; MAX_BEAM_ERROR_PROFILE_STATES];

/// Deterministic constant-memory P² quantile estimator used by experiment
/// diagnostics at the DSD wire rate.  It performs no allocation after
/// construction and never feeds a selection decision.
#[derive(Clone, Copy, Debug)]
pub(crate) struct StreamingQuantile {
    probability: f64,
    count: u64,
    initial: [f64; 5],
    heights: [f64; 5],
    positions: [f64; 5],
    desired: [f64; 5],
}

impl StreamingQuantile {
    pub(crate) fn new(probability: f64) -> Self {
        debug_assert!(probability.is_finite() && probability > 0.0 && probability < 1.0);
        Self {
            probability,
            count: 0,
            initial: [0.0; 5],
            heights: [0.0; 5],
            positions: [1.0, 2.0, 3.0, 4.0, 5.0],
            desired: [0.0; 5],
        }
    }

    pub(crate) fn observe(&mut self, value: f64) {
        if !value.is_finite() {
            return;
        }
        if self.count < 5 {
            self.initial[self.count as usize] = value;
            self.count += 1;
            if self.count == 5 {
                self.initial.sort_by(f64::total_cmp);
                self.heights = self.initial;
                let p = self.probability;
                self.desired = [1.0, 1.0 + 2.0 * p, 1.0 + 4.0 * p, 3.0 + 2.0 * p, 5.0];
            }
            return;
        }

        self.count = self.count.wrapping_add(1);
        let cell = if value < self.heights[0] {
            self.heights[0] = value;
            0
        } else if value < self.heights[1] {
            0
        } else if value < self.heights[2] {
            1
        } else if value < self.heights[3] {
            2
        } else if value <= self.heights[4] {
            3
        } else {
            self.heights[4] = value;
            3
        };
        for position in &mut self.positions[cell + 1..] {
            *position += 1.0;
        }
        let p = self.probability;
        let increments = [0.0, p / 2.0, p, (1.0 + p) / 2.0, 1.0];
        for (desired, increment) in self.desired.iter_mut().zip(increments) {
            *desired += increment;
        }

        for index in 1..4 {
            let delta = self.desired[index] - self.positions[index];
            let direction = if delta >= 1.0
                && self.positions[index + 1] - self.positions[index] > 1.0
            {
                1.0
            } else if delta <= -1.0 && self.positions[index - 1] - self.positions[index] < -1.0 {
                -1.0
            } else {
                continue;
            };
            let left_span = self.positions[index] - self.positions[index - 1];
            let right_span = self.positions[index + 1] - self.positions[index];
            let total_span = self.positions[index + 1] - self.positions[index - 1];
            let parabolic = self.heights[index]
                + direction / total_span
                    * ((left_span + direction) * (self.heights[index + 1] - self.heights[index])
                        / right_span
                        + (right_span - direction)
                            * (self.heights[index] - self.heights[index - 1])
                            / left_span);
            if self.heights[index - 1] < parabolic && parabolic < self.heights[index + 1] {
                self.heights[index] = parabolic;
            } else {
                let neighbor = (index as isize + direction as isize) as usize;
                self.heights[index] += direction * (self.heights[neighbor] - self.heights[index])
                    / (self.positions[neighbor] - self.positions[index]);
            }
            self.positions[index] += direction;
        }
    }

    pub(crate) fn estimate(&self) -> f64 {
        if self.count == 0 {
            return 0.0;
        }
        if self.count < 5 {
            let mut values = self.initial;
            values[..self.count as usize].sort_by(f64::total_cmp);
            let rank = ((self.count - 1) as f64 * self.probability).ceil() as usize;
            return values[rank.min(self.count as usize - 1)];
        }
        self.heights[2]
    }
}

/// Fixed-capacity state-space spectral weighting plus its tail-value terms.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct BeamErrorProfile {
    a: [[f64; MAX_BEAM_ERROR_PROFILE_STATES]; MAX_BEAM_ERROR_PROFILE_STATES],
    b: BeamErrorProfileState,
    c: BeamErrorProfileState,
    d: f64,
    p: [[f64; MAX_BEAM_ERROR_PROFILE_STATES]; MAX_BEAM_ERROR_PROFILE_STATES],
    h: BeamErrorProfileState,
    q: f64,
}

impl BeamErrorProfile {
    /// Causal filtered output for the supplied pre-advance state.
    #[inline]
    pub(crate) fn output(&self, state: &BeamErrorProfileState, error: f64) -> f64 {
        self.d.mul_add(error, dot(&self.c, state))
    }

    /// State after applying `error`, without modifying the supplied parent.
    #[inline]
    pub(crate) fn next_state(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> BeamErrorProfileState {
        let mut next = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
        for (row, next_value) in next.iter_mut().enumerate() {
            *next_value = self.b[row].mul_add(error, dot(&self.a[row], state));
        }
        next
    }

    /// Advance a selected survivor in place, returning its causal pre-advance output.
    #[inline]
    pub(crate) fn advance(&self, state: &mut BeamErrorProfileState, error: f64) -> f64 {
        let output = self.output(state, error);
        *state = self.next_state(state, error);
        output
    }

    #[inline]
    pub(crate) fn instantaneous_output_energy(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> f64 {
        let output = self.output(state, error);
        output * output
    }

    /// Exact zero-input output energy remaining after the current state.
    #[inline]
    pub(crate) fn remaining_zero_input_energy(&self, state: &BeamErrorProfileState) -> f64 {
        let mut energy = 0.0;
        for (row, state_value) in state.iter().copied().enumerate() {
            energy = state_value.mul_add(dot(&self.p[row], state), energy);
        }
        // A PSD quadratic can become a tiny negative through roundoff only.
        if energy < 0.0 && energy > -64.0 * f64::EPSILON {
            0.0
        } else {
            energy
        }
    }

    /// Single-count signed objective increment, using the generated hot terms.
    #[inline]
    pub(crate) fn tail_adjusted_energy_increment(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> f64 {
        (2.0 * error).mul_add(dot(&self.h, state), self.q * error * error)
    }

    /// Definition-form increment used by diagnostics and exact-oracle checks.
    #[inline]
    pub(crate) fn tail_adjusted_energy_increment_from_definition(
        &self,
        state: &BeamErrorProfileState,
        error: f64,
    ) -> f64 {
        let next = self.next_state(state, error);
        self.instantaneous_output_energy(state, error) + self.remaining_zero_input_energy(&next)
            - self.remaining_zero_input_energy(state)
    }

    #[cfg(test)]
    fn impulse_energy(&self) -> f64 {
        self.q
    }
}

#[inline]
fn dot(left: &BeamErrorProfileState, right: &BeamErrorProfileState) -> f64 {
    let mut result = 0.0;
    for index in 0..MAX_BEAM_ERROR_PROFILE_STATES {
        result = left[index].mul_add(right[index], result);
    }
    result
}

/// Reconstruction and complementary ultrasonic profiles for one wire family.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct BeamErrorProfiles {
    pub(crate) reconstruction: BeamErrorProfile,
    pub(crate) ultrasonic: BeamErrorProfile,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct UnsupportedBeamErrorWireRate {
    pub(crate) wire_rate: u32,
}

impl fmt::Display for UnsupportedBeamErrorWireRate {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "EcBeam2 supports only DSD64 wire rates 2822400 and 3072000 Hz (got {})",
            self.wire_rate
        )
    }
}

impl std::error::Error for UnsupportedBeamErrorWireRate {}

/// Select the physical-frequency profile from the actual DSD wire rate.
pub(crate) fn profiles_for_wire_rate(
    wire_rate: u32,
) -> Result<BeamErrorProfiles, UnsupportedBeamErrorWireRate> {
    match wire_rate {
        DSD64_44K_FAMILY_WIRE_RATE => Ok(BeamErrorProfiles {
            reconstruction: RECONSTRUCTION_2822400,
            ultrasonic: ULTRASONIC_2822400,
        }),
        DSD64_48K_FAMILY_WIRE_RATE => Ok(BeamErrorProfiles {
            reconstruction: RECONSTRUCTION_3072000,
            ultrasonic: ULTRASONIC_3072000,
        }),
        _ => Err(UnsupportedBeamErrorWireRate { wire_rate }),
    }
}

const IDENTITY_PROFILE_GRAMIAN: [[f64; MAX_BEAM_ERROR_PROFILE_STATES];
    MAX_BEAM_ERROR_PROFILE_STATES] = [
    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
];

// Generated by tools/gen_beam_error_profiles.py --rust; do not hand edit.
// wire_rate=2822400; sixth-order strict-minimum-phase linear-power fit
const RECONSTRUCTION_2822400: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.99366868234138228e-01,
            3.55789639519024092e-02,
            -3.51940698806174623e-14,
            -2.66453525910037570e-14,
            2.33146835171282873e-15,
            2.66453525910037570e-14,
        ],
        [
            -3.54443800288459371e-02,
            9.95586580705389634e-01,
            1.59321782158547975e-02,
            -2.92548034118880196e-02,
            -7.72745449824852049e-03,
            9.57789188976132522e-03,
        ],
        [
            1.17827525991990711e-03,
            -3.30962210708361376e-02,
            9.75043142319767742e-01,
            5.35348731456153359e-03,
            -2.11307502724631391e-02,
            2.61907775328928949e-02,
        ],
        [
            1.27934048050194071e-04,
            -3.59350117988899327e-03,
            -9.43269764203619326e-02,
            9.13275214618011977e-01,
            -3.81523765967610728e-02,
            4.72884490560065984e-02,
        ],
        [
            4.16793927081173811e-04,
            -1.17071998546402056e-02,
            -2.92431686073887469e-02,
            -5.92977737028238111e-02,
            9.69669425475885416e-01,
            9.74446239077959575e-02,
        ],
        [
            1.34153435398841548e-04,
            -3.76819568941301562e-03,
            -9.41249686170381530e-03,
            -1.90861707353706285e-02,
            -8.23535844059787997e-02,
            9.92676954652308652e-01,
        ],
    ],
    b: [
        1.38288593313494024e-01,
        2.67704140870491823e-04,
        2.34373709538167330e-03,
        2.54476847963327167e-04,
        8.29055333043605697e-04,
        2.66847988506968515e-04,
    ],
    c: [
        2.82173461395157296e-03,
        -7.92588589129163273e-02,
        -1.97979038847704070e-01,
        -4.01451580063300506e-01,
        -2.25825743513155680e-01,
        4.56411954068300374e-02,
    ],
    d: 5.61278362790229145e-03,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        1.38210563058241004e-01,
        4.65262994522879034e-03,
        1.12753644203594317e-03,
        -2.07039216503935534e-03,
        -5.46879807187183420e-04,
        6.77837141695683976e-04,
    ],
    q: 1.91616264488182649e-02,
};
const ULTRASONIC_2822400: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.95522989413672010e-01,
            9.45197204231273957e-02,
            -2.66453525910037570e-15,
            -3.55271367880050093e-15,
            3.38618022510672745e-15,
            -1.77635683940025046e-15,
        ],
        [
            -8.65605612723197165e-02,
            9.11693648027989023e-01,
            6.69061281644683925e-02,
            -1.68025377179397140e-02,
            -3.59163710202907716e-02,
            7.31573341289504242e-03,
        ],
        [
            -5.99663031165225107e-03,
            6.31591302591717474e-02,
            9.48775679659470295e-01,
            5.24402360262108402e-02,
            2.76888600004974172e-02,
            -5.63988823249594873e-03,
        ],
        [
            2.56027966477071021e-03,
            -2.69659839681875048e-02,
            -1.83856122615641028e-02,
            9.93612231265348367e-01,
            -9.80285170091693692e-03,
            1.99672315730659022e-03,
        ],
        [
            -3.00958835341875314e-03,
            3.16982993716829059e-02,
            -2.48041896492215974e-02,
            7.92647473845253109e-03,
            9.97668570320952575e-01,
            5.04296612008552358e-02,
        ],
        [
            1.71616487271185770e-03,
            -1.80753982000864781e-02,
            1.41441532772154013e-02,
            -4.51993293206282010e-03,
            -4.98372936158993293e-02,
            9.98345080458602818e-01,
        ],
    ],
    b: [
        -2.17608653999283364e-01,
        1.98249000982063162e-01,
        -1.49365777747945905e-01,
        6.37721759564979784e-02,
        -7.49636848941668266e-02,
        4.27467240156895675e-02,
    ],
    c: [
        3.72388148321523352e-02,
        -3.92215466761539899e-01,
        3.06911948393107148e-01,
        -9.80773748415342261e-02,
        4.57311511894633801e-03,
        -2.59737251402378244e-02,
    ],
    d: 9.27555018525684227e-01,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        -1.97895976752011954e-01,
        -2.17929756224100796e-01,
        1.57518712918317594e-01,
        -3.95586202294236841e-02,
        -8.45587794575163171e-02,
        1.72236078049108100e-02,
    ],
    q: 9.80838367533409139e-01,
};
// wire_rate=3072000; sixth-order strict-minimum-phase linear-power fit
const RECONSTRUCTION_3072000: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.99465591297859945e-01,
            3.26884048497149138e-02,
            -3.04201108747292892e-14,
            0.00000000000000000e+00,
            9.54791801177634625e-15,
            3.01980662698042579e-14,
        ],
        [
            -3.25751609651086516e-02,
            9.96003098508230988e-01,
            1.44426733638307603e-02,
            -2.70476867001505639e-02,
            -7.08142135574152398e-03,
            8.89290421472743731e-03,
        ],
        [
            9.96332827246603197e-04,
            -3.04634130325861611e-02,
            9.76771967647122041e-01,
            4.67060112719330789e-03,
            -1.94239237866802306e-02,
            2.43927151106539952e-02,
        ],
        [
            1.09180902325783097e-04,
            -3.33826491696790273e-03,
            -8.72926626072431933e-02,
            9.20295590315765133e-01,
            -3.49313710956764556e-02,
            4.38670884883585188e-02,
        ],
        [
            3.53697758742220134e-04,
            -1.08144995513606360e-02,
            -2.73154332569944536e-02,
            -5.46220698750238196e-02,
            9.72347422994416233e-01,
            8.98532791751414095e-02,
        ],
        [
            1.13949680039516170e-04,
            -3.48407286505640406e-03,
            -8.80012610440026113e-03,
            -1.75974182236515661e-02,
            -7.57437191293849066e-02,
            9.93573994208784894e-01,
        ],
    ],
    b: [
        1.32551722800681893e-01,
        2.55132645095435331e-04,
        2.24468788957294784e-03,
        2.45979097066092479e-04,
        7.96863311040134706e-04,
        2.56722914081113128e-04,
    ],
    c: [
        2.49960267048628029e-03,
        -7.64266984746572592e-02,
        -1.93039758457827421e-01,
        -3.86017350555521221e-01,
        -2.17153728908703381e-01,
        4.62460431390540050e-02,
    ],
    d: 5.63147945118966636e-03,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        1.32489225895339208e-01,
        4.07790778454135503e-03,
        1.06363554015340188e-03,
        -1.99193598912375969e-03,
        -5.21513658801742793e-04,
        6.54920923535080033e-04,
    ],
    q: 1.76075378981334595e-02,
};
const ULTRASONIC_3072000: BeamErrorProfile = BeamErrorProfile {
    a: [
        [
            9.96219987111086058e-01,
            8.68662033266556222e-02,
            2.66453525910037570e-15,
            0.00000000000000000e+00,
            -1.38777878078144568e-15,
            3.55271367880050093e-15,
        ],
        [
            -8.01096290668890237e-02,
            9.18732609233277597e-01,
            6.17423259219490594e-02,
            -1.57165295022032581e-02,
            -3.31656116173836280e-02,
            6.89868043221508742e-03,
        ],
        [
            -5.08982110064463977e-03,
            5.83723164717361853e-02,
            9.52798445232524327e-01,
            4.83890957101920094e-02,
            2.55613294632389687e-02,
            -5.31693627196361263e-03,
        ],
        [
            2.17320061063019801e-03,
            -2.49232244693648984e-02,
            -1.68078558064856005e-02,
            9.94101431474020858e-01,
            -9.05981873778921587e-03,
            1.88450600434464377e-03,
        ],
        [
            -2.55626183837524921e-03,
            2.93163398209347129e-02,
            -2.28998153547855243e-02,
            7.39039124782010781e-03,
            9.98024355668499563e-01,
            4.63243671168243054e-02,
        ],
        [
            1.45761064134854461e-03,
            -1.67165226374246176e-02,
            1.30577447290250032e-02,
            -4.21408823025679752e-03,
            -4.58330231776906821e-02,
            9.98580840803557246e-01,
        ],
    ],
    b: [
        -2.08612420057521508e-01,
        1.91084889775056610e-01,
        -1.43946901433577024e-01,
        6.14609998874289243e-02,
        -7.22944802206088033e-02,
        4.12231650523324014e-02,
    ],
    c: [
        3.29984306907863539e-02,
        -3.78440578021352336e-01,
        2.95610550716114695e-01,
        -9.54015389612785647e-02,
        3.36151833247158756e-03,
        -2.47172900173415755e-02,
    ],
    d: 9.33239451089434846e-01,
    p: IDENTITY_PROFILE_GRAMIAN,
    h: [
        -1.91225042712663690e-01,
        -2.08483964734728022e-01,
        1.51681853938419126e-01,
        -3.86106661321721292e-02,
        -8.14776797278498888e-02,
        1.69479303228524704e-02,
    ],
    q: 9.82392456119101309e-01,
};

#[cfg(test)]
mod tests {
    use super::*;

    fn all_profiles() -> [BeamErrorProfile; 4] {
        [
            RECONSTRUCTION_2822400,
            ULTRASONIC_2822400,
            RECONSTRUCTION_3072000,
            ULTRASONIC_3072000,
        ]
    }

    fn deterministic_error(sample: usize) -> f64 {
        let phase = sample as f64 * 0.173_205_080_756_887_73;
        (phase.sin() * 0.71 + (phase * 0.37).cos() * 0.19).clamp(-1.0, 1.0)
    }

    #[test]
    fn beam_error_profile_selects_only_dsd64_wire_families() {
        assert!(profiles_for_wire_rate(DSD64_44K_FAMILY_WIRE_RATE).is_ok());
        assert!(profiles_for_wire_rate(DSD64_48K_FAMILY_WIRE_RATE).is_ok());
        for unsupported in [0, 44_100, 5_644_800, 6_144_000, 11_289_600, 12_288_000] {
            let error = profiles_for_wire_rate(unsupported).unwrap_err();
            assert_eq!(error.wire_rate, unsupported);
        }
    }

    #[test]
    fn beam_error_profile_hot_increment_matches_lyapunov_definition() {
        for profile in all_profiles() {
            let mut state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            for sample in 0..4096 {
                let error = deterministic_error(sample);
                let hot = profile.tail_adjusted_energy_increment(&state, error);
                let definition =
                    profile.tail_adjusted_energy_increment_from_definition(&state, error);
                let tolerance = 2.0e-9 * (1.0 + hot.abs() + definition.abs());
                assert!(
                    (hot - definition).abs() <= tolerance,
                    "{hot} != {definition}"
                );
                profile.advance(&mut state, error);
            }
        }
    }

    #[test]
    fn beam_error_profile_telescopes_without_counting_terminal_tail_twice() {
        for profile in all_profiles() {
            let mut state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut objective = 0.0;
            let mut observed = 0.0;
            let initial_tail = profile.remaining_zero_input_energy(&state);
            for sample in 0..2048 {
                let error = deterministic_error(sample);
                objective += profile.tail_adjusted_energy_increment(&state, error);
                observed += profile.instantaneous_output_energy(&state, error);
                profile.advance(&mut state, error);
            }
            let expected = observed + profile.remaining_zero_input_energy(&state) - initial_tail;
            assert!((objective - expected).abs() <= 2.0e-7 * (1.0 + expected.abs()));
        }
    }

    #[test]
    fn beam_error_profile_impulse_energy_is_q_and_tail_converges() {
        for profile in all_profiles() {
            let mut state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut energy = 0.0;
            for sample in 0..16_384 {
                let error = if sample == 0 { 1.0 } else { 0.0 };
                energy += profile.instantaneous_output_energy(&state, error);
                profile.advance(&mut state, error);
            }
            let tail = profile.remaining_zero_input_energy(&state);
            assert!(tail < 1.0e-20, "tail did not converge: {tail}");
            assert!((energy + tail - profile.impulse_energy()).abs() < 2.0e-10);
        }
    }

    #[test]
    fn beam_error_profile_streaming_matches_impulse_convolution() {
        for profile in all_profiles() {
            let mut impulse_state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let impulse: Vec<_> = (0..256)
                .map(|sample| {
                    let error = if sample == 0 { 1.0 } else { 0.0 };
                    let output = profile.output(&impulse_state, error);
                    profile.advance(&mut impulse_state, error);
                    output
                })
                .collect();
            let input: Vec<_> = (0..128).map(deterministic_error).collect();
            let mut streaming_state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            for sample in 0..input.len() {
                let streaming = profile.output(&streaming_state, input[sample]);
                profile.advance(&mut streaming_state, input[sample]);
                let convolution: f64 = (0..=sample)
                    .map(|lag| impulse[lag] * input[sample - lag])
                    .sum();
                assert!((streaming - convolution).abs() < 2.0e-12);
            }
        }
    }

    #[test]
    fn beam_error_profile_power_pair_is_complementary() {
        for wire_rate in [DSD64_44K_FAMILY_WIRE_RATE, DSD64_48K_FAMILY_WIRE_RATE] {
            let profiles = profiles_for_wire_rate(wire_rate).unwrap();
            assert!(
                (profiles.reconstruction.impulse_energy() + profiles.ultrasonic.impulse_energy()
                    - 1.0)
                    .abs()
                    < 1.0e-7
            );

            let mut low_state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut high_state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut low = Vec::with_capacity(8192);
            let mut high = Vec::with_capacity(8192);
            for sample in 0..8192 {
                let error = if sample == 0 { 1.0 } else { 0.0 };
                low.push(profiles.reconstruction.output(&low_state, error));
                high.push(profiles.ultrasonic.output(&high_state, error));
                profiles.reconstruction.advance(&mut low_state, error);
                profiles.ultrasonic.advance(&mut high_state, error);
            }
            for lag in 1..=32 {
                let autocorrelation: f64 = (0..low.len() - lag)
                    .map(|sample| {
                        low[sample] * low[sample + lag] + high[sample] * high[sample + lag]
                    })
                    .sum();
                assert!(
                    autocorrelation.abs() < 2.0e-9,
                    "lag {lag}: {autocorrelation}"
                );
            }
        }
    }

    #[test]
    fn beam_error_profile_signed_increment_can_be_negative() {
        for profile in all_profiles() {
            let mut state = [0.0; MAX_BEAM_ERROR_PROFILE_STATES];
            let mut saw_negative = false;
            for sample in 0..4096 {
                let error = deterministic_error(sample);
                saw_negative |= profile.tail_adjusted_energy_increment(&state, error) < 0.0;
                profile.advance(&mut state, error);
            }
            assert!(saw_negative);
        }
    }

    #[test]
    fn streaming_quantile_tracks_extreme_calibration_percentiles() {
        let mut p999 = StreamingQuantile::new(0.999);
        let mut p9999 = StreamingQuantile::new(0.9999);
        for value in 0..100_000 {
            let value = value as f64;
            p999.observe(value);
            p9999.observe(value);
        }
        assert!((p999.estimate() - 99_899.0).abs() < 250.0);
        assert!((p9999.estimate() - 99_989.0).abs() < 100.0);
        assert!(p9999.estimate() >= p999.estimate());
    }
}
