from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np


IDENTITY = "SplitPhase128kV5-E2v3-audio-high-resolution-experimental"
STABLE_ID = 37


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _write_f64le(path: Path, values: np.ndarray) -> dict[str, Any]:
    payload = np.asarray(values, dtype="<f8").tobytes(order="C")
    path.write_bytes(payload)
    return {
        "file": path.name,
        "coefficient_count": int(np.asarray(values).size),
        "byte_length": len(payload),
        "sha256": hashlib.sha256(payload).hexdigest(),
    }


def _write_generated_rust(asset_dir: Path, manifest: dict[str, Any]) -> None:
    files = manifest["files"]
    alignment = manifest["alignment"]
    cleanup_counts = ", ".join(str(item["coefficient_count"]) for item in files["cleanups"])
    cleanup_hashes = ", ".join(f'"{item["sha256"]}"' for item in files["cleanups"])
    source = "\n".join(
        (
            "// @generated by tools/split_phase_v5/export_e2v3_experimental.py; do not edit.",
            f"const SPLIT_PHASE_E2V3_CHARACTER_COEFFICIENTS: usize = {files['character']['coefficient_count']};",
            f"const SPLIT_PHASE_E2V3_CLEANUP_COEFFICIENTS: [usize; 7] = [{cleanup_counts}];",
            f"const SPLIT_PHASE_E2V3_RATIONAL_147_160_COEFFICIENTS: usize = {files['rational_147_160']['coefficient_count']};",
            f"const SPLIT_PHASE_E2V3_RATIONAL_160_147_COEFFICIENTS: usize = {files['rational_160_147']['coefficient_count']};",
            f"const SPLIT_PHASE_E2V3_FULL_RATE_ORIGIN: usize = {alignment['full_rate_origin']};",
            f"const SPLIT_PHASE_E2V3_PHASE0_PREPAD: usize = {alignment['phase0_prepad']};",
            f"const SPLIT_PHASE_E2V3_PHASE1_PREPAD: usize = {alignment['phase1_prepad']};",
            f"const SPLIT_PHASE_E2V3_DECIMATION_PREPAD: usize = {alignment['decimation_prepad']};",
            "#[allow(dead_code)]",
            f'const SPLIT_PHASE_E2V3_CHARACTER_SHA256: &str = "{files["character"]["sha256"]}";',
            "#[allow(dead_code)]",
            f"const SPLIT_PHASE_E2V3_CLEANUP_SHA256: [&str; 7] = [{cleanup_hashes}];",
            "#[allow(dead_code)]",
            f'const SPLIT_PHASE_E2V3_RATIONAL_147_160_SHA256: &str = "{files["rational_147_160"]["sha256"]}";',
            "#[allow(dead_code)]",
            f'const SPLIT_PHASE_E2V3_RATIONAL_160_147_SHA256: &str = "{files["rational_160_147"]["sha256"]}";',
            "",
        )
    )
    (asset_dir / "generated.rs").write_text(source, encoding="utf-8")


def export(source_dir: Path, asset_dir: Path) -> dict[str, Any]:
    report_path = source_dir / "e2v3_report.json"
    report = json.loads(report_path.read_text(encoding="utf-8"))
    full = report.get("full_pipeline_result")
    if report.get("identity") != IDENTITY:
        raise RuntimeError("E2v3 export refused: unexpected source identity")
    if not report.get("accepted") or not isinstance(full, dict) or not full.get("accepted"):
        raise RuntimeError("E2v3 export refused: full-pipeline result is not accepted")
    if report.get("production_promoted") or full.get("production_promoted"):
        raise RuntimeError("E2v3 export refused: experimental source claims production promotion")

    winner = source_dir / "winner_full_pipeline"
    winner_result_path = winner / "result.json"
    winner_result = json.loads(winner_result_path.read_text(encoding="utf-8"))
    if not winner_result.get("accepted") or winner_result.get("production_promoted"):
        raise RuntimeError("E2v3 export refused: winner audit is not accepted experimental data")

    origin = int(json.loads((winner / "alignment.json").read_text(encoding="utf-8"))["full_rate_origin"])
    alignment = {
        "full_rate_origin": origin,
        "phase0_prepad": 131_072 - (origin + 1) // 2,
        "phase1_prepad": 131_072 - origin // 2,
        "decimation_prepad": 262_144 - origin,
    }
    character = np.load(winner / "character.npy")
    rational_147_160 = np.load(winner / "rational_147_160.npy")
    rational_160_147 = np.load(winner / "rational_160_147.npy")
    with np.load(winner / "cleanup_optimized.npz") as saved:
        cleanups = [np.asarray(saved[f"stage_{index}"], dtype=np.float64) for index in range(1, 8)]
    expected_shapes = [(262_145,), (164_000,), (301_203,)]
    for label, values, expected in (
        ("character", character, expected_shapes[0]),
        ("rational 147/160", rational_147_160, expected_shapes[1]),
        ("rational 160/147", rational_160_147, expected_shapes[2]),
    ):
        if values.shape != expected or not np.all(np.isfinite(values)):
            raise RuntimeError(f"E2v3 export refused: invalid {label} array")
    expected_cleanup = (509, 253, 125, 61, 61, 61, 61)
    if tuple(values.size for values in cleanups) != expected_cleanup:
        raise RuntimeError("E2v3 export refused: cleanup shape mismatch")

    asset_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "character": _write_f64le(asset_dir / "character_full_rate.f64le", character),
        "cleanups": [
            _write_f64le(asset_dir / f"cleanup_stage_{index}.f64le", values)
            for index, values in enumerate(cleanups, 1)
        ],
        "rational_147_160": _write_f64le(
            asset_dir / "rational_147_160.f64le", rational_147_160
        ),
        "rational_160_147": _write_f64le(
            asset_dir / "rational_160_147.f64le", rational_160_147
        ),
    }
    metrics = full["comparison"]["d_metrics"]
    manifest = {
        "format_version": 1,
        "identity": IDENTITY,
        "runtime_name": "SplitPhase128kE2v3",
        "stable_id": STABLE_ID,
        "experimental": True,
        "production_promoted": False,
        "accepted_full_pipeline": True,
        "endianness": "little",
        "scalar": "IEEE-754 binary64",
        "source": {
            "e2v3_report_sha256": _sha256(report_path),
            "winner_result_sha256": _sha256(winner_result_path),
            "pareto_improvement_count": int(full["comparison"]["pareto_improvement_count"]),
        },
        "alignment": alignment,
        "files": files,
        "audition_metrics": {
            key: metrics[key]
            for key in (
                "pre_energy_before_dominant_peak_db",
                "step_response_overshoot",
                "group_delay_curvature_max_abs_samples_per_ln_hz_squared",
                "worst_interpolation_image_db",
                "worst_independent_decimation_alias_db",
                "worst_complex_passband_error",
            )
        },
    }
    (asset_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (asset_dir / "experimental_audit.json").write_text(
        json.dumps(full, indent=2) + "\n", encoding="utf-8"
    )
    _write_generated_rust(asset_dir, manifest)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-dir", type=Path, required=True)
    parser.add_argument("--asset-dir", type=Path)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    asset_dir = (arguments.asset_dir or root / "assets/filters/split_phase_e2v3").resolve()
    print(json.dumps(export(arguments.source_dir.resolve(), asset_dir), indent=2))


if __name__ == "__main__":
    main()
