from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path
from typing import Any

import numpy as np


IDENTITY = "SplitPhase128kE3-P-experimental"
RUNTIME_NAME = "SplitPhase128kE3"
STABLE_ID = 38


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _asset_record(path: Path) -> dict[str, Any]:
    byte_length = path.stat().st_size
    if byte_length % 8:
        raise RuntimeError(f"asset is not binary64-aligned: {path}")
    values = np.fromfile(path, dtype="<f8")
    if values.size == 0 or not np.all(np.isfinite(values)):
        raise RuntimeError(f"asset contains invalid coefficients: {path}")
    return {
        "file": path.name,
        "coefficient_count": int(values.size),
        "byte_length": byte_length,
        "sha256": _sha256(path),
    }


def _write_generated_rust(asset_dir: Path, manifest: dict[str, Any]) -> None:
    files = manifest["files"]
    alignment = manifest["alignment"]
    cleanup_counts = ", ".join(str(item["coefficient_count"]) for item in files["cleanups"])
    cleanup_hashes = ", ".join(f'"{item["sha256"]}"' for item in files["cleanups"])
    source = "\n".join(
        (
            "// @generated by tools/split_phase_v6/export_e3_experimental.py; do not edit.",
            f"const SPLIT_PHASE_E3_CHARACTER_COEFFICIENTS: usize = {files['character']['coefficient_count']};",
            f"const SPLIT_PHASE_E3_CLEANUP_COEFFICIENTS: [usize; 7] = [{cleanup_counts}];",
            f"const SPLIT_PHASE_E3_RATIONAL_147_160_COEFFICIENTS: usize = {files['rational_147_160']['coefficient_count']};",
            f"const SPLIT_PHASE_E3_RATIONAL_160_147_COEFFICIENTS: usize = {files['rational_160_147']['coefficient_count']};",
            f"const SPLIT_PHASE_E3_FULL_RATE_ORIGIN: usize = {alignment['full_rate_origin']};",
            f"const SPLIT_PHASE_E3_PHASE0_PREPAD: usize = {alignment['phase0_prepad']};",
            f"const SPLIT_PHASE_E3_PHASE1_PREPAD: usize = {alignment['phase1_prepad']};",
            f"const SPLIT_PHASE_E3_DECIMATION_PREPAD: usize = {alignment['decimation_prepad']};",
            "#[allow(dead_code)]",
            f'const SPLIT_PHASE_E3_CHARACTER_SHA256: &str = "{files["character"]["sha256"]}";',
            "#[allow(dead_code)]",
            f"const SPLIT_PHASE_E3_CLEANUP_SHA256: [&str; 7] = [{cleanup_hashes}];",
            "#[allow(dead_code)]",
            f'const SPLIT_PHASE_E3_RATIONAL_147_160_SHA256: &str = "{files["rational_147_160"]["sha256"]}";',
            "#[allow(dead_code)]",
            f'const SPLIT_PHASE_E3_RATIONAL_160_147_SHA256: &str = "{files["rational_160_147"]["sha256"]}";',
            "",
        )
    )
    (asset_dir / "generated.rs").write_text(source, encoding="utf-8")


def export(
    root: Path,
    work_dir: Path,
    asset_dir: Path,
    candidate_id: str | None = None,
    report_name: str = "e3_phase_search.json",
) -> dict[str, Any]:
    source_assets = root / "assets/filters/split_phase_e2v3"
    report_path = work_dir / report_name
    report = json.loads(report_path.read_text(encoding="utf-8"))
    if candidate_id is None:
        if "winner" not in report:
            raise RuntimeError("E3 export requires --candidate-id for a Pareto-only report")
        winner = report["winner"]
        winner_path = work_dir / "winner_character.f64le"
    else:
        winner = next(
            (record for record in report["pareto"] if record["identifier"] == candidate_id),
            None,
        )
        if winner is None:
            raise RuntimeError(f"E3 export refused: {candidate_id!r} is not a Pareto candidate")
        winner_path = work_dir / winner["character_file"]
    if report.get("production_promoted"):
        raise RuntimeError("E3 export refused: search claims production promotion")
    passed = winner.get("passes_safety", winner.get("passes_impulse_guards", False))
    if not passed:
        raise RuntimeError("E3 export refused: winner did not pass safety gates")
    if _sha256(winner_path) != winner["character_sha256"]:
        raise RuntimeError("E3 export refused: winner character hash mismatch")
    metrics = winner["metrics"]
    if "hard_guards" in report:
        if (
            metrics["pre_energy_db_total"] > -4.85
            or metrics["maximum_pre_lobe_db_peak"] > -22.5
            or metrics["main_lobe_width_us"] > 62.5
            or metrics["step_overshoot_percent"]
            > report["hard_guards"]["proxy_step_overshoot_percent_max"]
            or metrics["decay_120_ms"] > 7.0
            or winner["maximum_magnitude_delta_db_0_20khz"]
            > report["hard_guards"]["maximum_magnitude_delta_db_0_20khz"]
        ):
            raise RuntimeError("E3 export refused: P2 finalist no longer satisfies hard guards")
    elif (
        metrics["pre_energy_db_total"] > -4.90
        or metrics["maximum_pre_lobe_db_peak"] > -17.0
        or metrics["main_lobe_width_us"] > 68.75
        or metrics["decay_120_ms"] > 10.0
        or metrics["step_undershoot_percent"]
        > report["baseline_metrics"]["step_undershoot_percent"]
    ):
        raise RuntimeError("E3 export refused: winner no longer satisfies safety gates")

    asset_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(winner_path, asset_dir / "character_full_rate.f64le")
    for index in range(1, 8):
        shutil.copyfile(
            source_assets / f"cleanup_stage_{index}.f64le",
            asset_dir / f"cleanup_stage_{index}.f64le",
        )
    for name in ("rational_147_160.f64le", "rational_160_147.f64le"):
        shutil.copyfile(source_assets / name, asset_dir / name)

    source_manifest = json.loads((source_assets / "manifest.json").read_text(encoding="utf-8"))
    files = {
        "character": _asset_record(asset_dir / "character_full_rate.f64le"),
        "cleanups": [
            _asset_record(asset_dir / f"cleanup_stage_{index}.f64le") for index in range(1, 8)
        ],
        "rational_147_160": _asset_record(asset_dir / "rational_147_160.f64le"),
        "rational_160_147": _asset_record(asset_dir / "rational_160_147.f64le"),
    }
    manifest = {
        "format_version": 1,
        "identity": (
            "SplitPhase128kE3-P3-experimental"
            if "P3" in report.get("identity", "")
            else "SplitPhase128kE3-P2-experimental"
            if "hard_guards" in report
            else IDENTITY
        ),
        "runtime_name": RUNTIME_NAME,
        "stable_id": STABLE_ID,
        "experimental": True,
        "production_promoted": False,
        "accepted_full_pipeline": False,
        "endianness": "little",
        "scalar": "IEEE-754 binary64",
        "source": {
            "baseline_runtime_name": source_manifest["runtime_name"],
            "baseline_manifest_sha256": _sha256(source_assets / "manifest.json"),
            "phase_search_report_sha256": _sha256(report_path),
            "candidate_identifier": winner["identifier"],
        },
        "alignment": source_manifest["alignment"],
        "files": files,
        "proxy_timing_metrics": metrics,
        "promotion_requirements": [
            "exact native and matched-band timing reports",
            "complete interpolation and decimation certification",
            "complete EcBeam2 and standard-modulator DSD matrix",
            "determinism and real-time target verification",
        ],
    }
    (asset_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    (asset_dir / "experimental_audit.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    _write_generated_rust(asset_dir, manifest)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Export the experimental Split Phase E3 bundle")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--work-dir", type=Path)
    parser.add_argument("--asset-dir", type=Path)
    parser.add_argument("--candidate-id")
    parser.add_argument("--report-name", default="e3_phase_search.json")
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    work_dir = (arguments.work_dir or root / "tools/split_phase_v6/work-e3-p").resolve()
    asset_dir = (arguments.asset_dir or root / "assets/filters/split_phase_e3").resolve()
    print(
        json.dumps(
            export(
                root,
                work_dir,
                asset_dir,
                arguments.candidate_id,
                arguments.report_name,
            ),
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
