from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import platform
import subprocess
from pathlib import Path
from typing import Any

import cvxpy
import numpy as np
import scipy


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _clean_commit(root: Path) -> str:
    status = subprocess.check_output(["git", "status", "--porcelain", "--untracked-files=all"], cwd=root, text=True)
    if status:
        raise RuntimeError("production export refused: source tree is dirty")
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip()


def _write_f64le(path: Path, values: np.ndarray) -> dict[str, Any]:
    payload = np.asarray(values, dtype="<f8").tobytes(order="C")
    path.write_bytes(payload)
    return {"file": path.name, "coefficient_count": int(np.asarray(values).size), "byte_length": len(payload), "sha256": hashlib.sha256(payload).hexdigest()}


def _write_generated_rust(asset_dir: Path, manifest: dict[str, Any]) -> None:
    files = manifest["files"]
    cleanup_counts = ", ".join(str(item["coefficient_count"]) for item in files["cleanups"])
    cleanup_hashes = ", ".join('"' + item["sha256"] + '"' for item in files["cleanups"])
    alignment = manifest["alignment"]
    source = "\n".join(
        (
            "// @generated by tools/split_phase_v4/export_assets.py; do not edit.",
            "const SPLIT_PHASE_V4_CHARACTER_COEFFICIENTS: usize = " + str(files["character"]["coefficient_count"]) + ";",
            "const SPLIT_PHASE_V4_CLEANUP_COEFFICIENTS: [usize; 7] = [" + cleanup_counts + "];",
            "const SPLIT_PHASE_V4_RATIONAL_147_160_COEFFICIENTS: usize = " + str(files["rational_147_160"]["coefficient_count"]) + ";",
            "const SPLIT_PHASE_V4_RATIONAL_160_147_COEFFICIENTS: usize = " + str(files["rational_160_147"]["coefficient_count"]) + ";",
            "const SPLIT_PHASE_V4_FULL_RATE_ORIGIN: usize = " + str(alignment["full_rate_origin"]) + ";",
            "const SPLIT_PHASE_V4_PHASE0_PREPAD: usize = " + str(alignment["phase0_prepad"]) + ";",
            "const SPLIT_PHASE_V4_PHASE1_PREPAD: usize = " + str(alignment["phase1_prepad"]) + ";",
            "const SPLIT_PHASE_V4_DECIMATION_PREPAD: usize = " + str(alignment["decimation_prepad"]) + ";",
            '#[allow(dead_code)]',
            'const SPLIT_PHASE_V4_CHARACTER_SHA256: &str = "' + files["character"]["sha256"] + '";',
            '#[allow(dead_code)]',
            "const SPLIT_PHASE_V4_CLEANUP_SHA256: [&str; 7] = [" + cleanup_hashes + "];",
            '#[allow(dead_code)]',
            'const SPLIT_PHASE_V4_RATIONAL_147_160_SHA256: &str = "' + files["rational_147_160"]["sha256"] + '";',
            '#[allow(dead_code)]',
            'const SPLIT_PHASE_V4_RATIONAL_160_147_SHA256: &str = "' + files["rational_160_147"]["sha256"] + '";',
            "",
        )
    )
    (asset_dir / "generated.rs").write_text(source)


def export(root: Path, work_dir: Path, asset_dir: Path) -> dict[str, Any]:
    commit = _clean_commit(root)
    magnitude_report = json.loads((work_dir / "magnitude_order_512.json").read_text())
    certification = json.loads((work_dir / "certification.json").read_text())
    build_report = json.loads((work_dir / "build_report.json").read_text())
    runtime_report = json.loads((work_dir / "runtime_capture.json").read_text())
    reproducibility = json.loads((work_dir / "reproducibility.json").read_text())
    alignment = json.loads((work_dir / "alignment.json").read_text())
    if not magnitude_report.get("accepted"):
        raise RuntimeError("production export refused: genuine PSD magnitude was not accepted")
    if not certification.get("accepted"):
        raise RuntimeError("production export refused: certification is not accepted")
    if not reproducibility.get("accepted") or reproducibility.get("first_character_sha256") != reproducibility.get("clean_resume_character_sha256"):
        raise RuntimeError("production export refused: clean CPU resume did not reproduce the character hash")
    asset_dir.mkdir(parents=True, exist_ok=True)
    files = {
        "character": _write_f64le(asset_dir / "character_full_rate.f64le", np.load(work_dir / "character_optimized.npy")),
        "rational_147_160": _write_f64le(asset_dir / "rational_147_160.f64le", np.load(work_dir / "rational_147_160.npy")),
        "rational_160_147": _write_f64le(asset_dir / "rational_160_147.f64le", np.load(work_dir / "rational_160_147.npy")),
    }
    cleanup = np.load(work_dir / "cleanup_optimized.npz")
    files["cleanups"] = [_write_f64le(asset_dir / ("cleanup_stage_" + str(index) + ".f64le"), cleanup["stage_" + str(index)]) for index in range(1, 8)]
    lock = root / "tools/split_phase_v4/requirements.lock"
    final_solver = magnitude_report["exchange_history"][-1]["lexicographic_history"][-1]
    manifest = {
        "format_version": 2,
        "identity": "SplitPhase128kV4",
        "stable_id": 36,
        "endianness": "little",
        "scalar": "IEEE-754 binary64",
        "source_tree_dirty": False,
        "source_git_commit": commit,
        "generator_git_commit": commit,
        "dependency_lock_sha256": _sha256(lock),
        "seed": 128004,
        "all_seeds": {"production": 128004, "reference_model": 128004},
        "generated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "platform": platform.platform(),
        "python": platform.python_version(),
        "solver": {
            "name": magnitude_report["solver"],
            "status": final_solver["status"],
            "primal_objective": final_solver["primal_objective"],
            "dual_objective": final_solver["dual_objective"],
            "primal_dual_gap": final_solver["primal_dual_gap"],
            "psd_minimum_eigenvalue": magnitude_report["psd_minimum_eigenvalue"],
        },
        "alignment": alignment,
        "files": files,
        "active_frequency_sets_hz": magnitude_report.get("active_frequency_sets_hz"),
        "objective_histories": {
            "magnitude_exchange": magnitude_report["exchange_history"],
            "outer_joint": build_report.get("outer_joint_history"),
            "character_lawson": build_report.get("character", {}).get("iterations"),
            "cleanup_socp": build_report.get("cleanup", {}).get("stages"),
            "rational_joint": build_report.get("rational"),
        },
        "runtime_certification": runtime_report,
        "mathematical_certification": certification,
        "clean_cpu_resume_reproducibility": reproducibility,
        "generator_versions": {"numpy": np.__version__, "scipy": scipy.__version__, "cvxpy": cvxpy.__version__},
    }
    (asset_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    _write_generated_rust(asset_dir, manifest)
    (asset_dir / "certification.json").write_text(json.dumps(certification, indent=2) + "\n")
    development_marker = asset_dir / "DEVELOPMENT_CHECKPOINT.json"
    if development_marker.exists():
        development_marker.unlink()
    comparison_path = work_dir / "comparison_abcd.json"
    if comparison_path.exists():
        (asset_dir / "comparison_abcd.json").write_bytes(comparison_path.read_bytes())
    return manifest


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--work-dir", type=Path)
    parser.add_argument("--asset-dir", type=Path)
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    print(json.dumps(export(root, arguments.work_dir or root / "tools/split_phase_v4/work", arguments.asset_dir or root / "assets/filters/split_phase_v4"), indent=2))
